### ISSUE TITLE
Add a way of passing connection_scopes and other params

### ISSUE THREAD

**Issue by eugeniop** [auth0/Xamarin.Auth0Client#11]
Is it possible with today's API to pass any custom parameters (like `connection_scopes`)? 

This leads me to think that it can't:

https://github.com/auth0/Xamarin.Auth0Client/blob/master/src/Auth0Client/Auth0Constants.cs#L18

**Comment by sandrinodimattia** [comment]
Indeed. We need something like this: https://github.com/auth0/Auth0.Windows8.Cs/commit/c51d4615d32b51266c835d6054cf77058f0ff113

**Comment by rolodato** [comment]
Same for `access_token` (for linking accounts). Requested here: https://ask.auth0.com/t/how-to-link-accounts/1142/7

**Comment by JoeCooper** [comment]
This software is dead, isn't it?

**Comment by jerriep** [comment]
@JoeCooper Please see new quickstart which uses the Auth0 OIDC Client

**Comment by jerriep** [comment]
Closing this as the Xamarin components have been replaced with the new Auth0 OIDC Client:
https://github.com/auth0/auth0-oidc-client-net

For all interested, see the new updated Xamarin quickstart:
https://auth0.com/docs/quickstart/native/xamarin
