### ISSUE TITLE
Auth0 Client requires specific versions of Json.NET and Xamarin.Auth

### ISSUE THREAD

**Issue by zakisaadeh-pariveda** [auth0/Xamarin.Auth0Client#13]
When adding the client to my solution, I noticed that it was forcing me to downgrade my solution to use a specific version of Json.NET (v4.5). We need the client to not require specific versions of its dependencies when that's not necessary.

**Comment by hzalaz** [comment]
@zakisaadeh-pariveda there is a new version in Xamarin Store. Let us know if it fixes your issue with Json.Net.

**Comment by zakisaadeh-pariveda** [comment]
@hzalaz that did it. Thanks.
