### ISSUE TITLE
Xamarin Components are so 2015

### ISSUE THREAD

**Issue by ChaseFlorell** [auth0/Xamarin.Auth0Client#23]
Wondering if we can include Nuget support for the client?

```
> Install-Package Xamarin.Auth0Client
```

FTW!

**Comment by Architekt909** [comment]
Agreed, there's no reason it shouldn't have a NuGet package at this point.

**Comment by jerriep** [comment]
This library has been replaced with the Auth0 OIDC Client.

Please see https://auth0.com/docs/quickstart/native/xamarin for latest Quickstart
