### ISSUE TITLE
Recommended way to differentiate Login from Signup?

### ISSUE THREAD

**Issue by ChaseFlorell** [auth0/Xamarin.Auth0Client#24]
Using this particular library, what's the recommended approach to differentiating login from signup? As I see it, out of the box, if a user isn't registered, using the LoginAsync endpoint will register them.

I want different behaviour based on if they're signing up or already registered and simply logging in.

**Comment by jerriep** [comment]
This is best handled in the Hosted Login page, and not relevant to this library. Please open a proper support issue. See https://support.auth0.com/

Also, this library has been deprecated. See Quickstart on how to use new Auth0 OIDC Client:
https://auth0.com/docs/quickstart/native/xamarin
