### ISSUE TITLE
disallowed_useragent for Google Social on iOS

### ISSUE THREAD

**Issue by mveroukis** [auth0/Xamarin.Auth0Client#26]
I created a new social connection on the Auth0 site and added the client ID and secret from Google's dev console. Using this SDK, it works fine on Android but on iOS I get:

> 403 - That's an error
> 
> Error: disallowed_useragent
> 
> This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view).
> 

It seems that a SafariViewController is needed to get around this. Has anyone been able to do this or work around it? Not signing in with Google on iOS makes Auth0 rather useless, no?

**Comment by AntRemo** [comment]
I am currently looking for a solution to this as well.

**Comment by farcasclaudiu** [comment]
+1

**Comment by Johnnyrook777** [comment]
+1

**Comment by alexandra-valkova** [comment]
+1

**Comment by jerriep** [comment]
Hi all, can you please look at this example of the new Auth0 OIDC Client:
https://github.com/auth0-community/auth0-xamarin-ios-oidc-samples/tree/master/Quickstart/00-Starter-Seed/iOSSample

The quickstart for this is not yet published, unfortunately, but the sample should be fairly straightforward. Steps are more or less as follows:

1. Install the NuGet package `Auth0.OidcClient.iOS`
2. Register the URL Scheme with your Bundle Identifier: https://github.com/auth0-community/auth0-xamarin-ios-oidc-samples/blob/master/Quickstart/00-Starter-Seed/iOSSample/iOSSample/Info.plist#L40-L49
3. Call `ActivityMediator.Instance.Send(url.AbsoluteString)` in `AppDelegate.OpenUrl`: https://github.com/auth0-community/auth0-xamarin-ios-oidc-samples/blob/master/Quickstart/00-Starter-Seed/iOSSample/iOSSample/AppDelegate.cs#L23
4. Initialize the `Auth0Client` in your View Controller: https://github.com/auth0-community/auth0-xamarin-ios-oidc-samples/blob/master/Quickstart/00-Starter-Seed/iOSSample/iOSSample/MyViewController.cs#L35-L40
5. Call `LoginAsync`: https://github.com/auth0-community/auth0-xamarin-ios-oidc-samples/blob/master/Quickstart/00-Starter-Seed/iOSSample/iOSSample/MyViewController.cs#L42

You can find the docs at https://auth0.github.io/auth0-oidc-client-net/, though it is not 100% up to date yet.

**Comment by jerriep** [comment]
An updated Xamarin quickstart is available:
https://auth0.com/docs/quickstart/native/xamarin

Please use that with the new Auth0 OIDC Client https://auth0.github.io/auth0-oidc-client-net/
