### ISSUE TITLE
Is this library still working?

### ISSUE THREAD

**Issue by Nyholm** [auth0/Xamarin.Auth0Client#28]
There has been no updates since 2015. There is no release, no installation instruction nor can I find a nuget. 

Could the maintainers give this library some love for us that are new to Auth0 and Xamarin?

**Comment by jerriep** [comment]
Please have a look at our new OIDC Client library:
https://github.com/auth0/auth0-oidc-client-net

For help in implementing this in Xamarin, review this Quickstart document:
https://auth0.com/docs/quickstart/native/xamarin

**Comment by Nyholm** [comment]
Thank you for your quick reply!

**Comment by dagostinelli** [comment]
@jerriep If you have the rights, could you please change the readme for this repo to mark it as obsolete and redirect people to the other client libraries?  It's super-confusing to find these old repos.

**Comment by jerriep** [comment]
@dagostinelli updated
