### ISSUE TITLE
Samples do not compile out of the box

### ISSUE THREAD

**Issue by dagostinelli** [auth0/Xamarin.Auth0Client#29]
I recommend that you guys include a CI config in every single of your GitHub repos.  I'm new to Auth0 and I'm now on my 4th or 5th day and STILL do not have anything working correctly in my Xamarin project.

The samples in this github repo don't compile with a naked VS2017 install.  The .NET targeting is a little off, the Xamarin.Auth.Android reference is not correct, the packages.config has no way to fix.  I can't fix this myself unless I'm already an experienced Auth0 developer.  

Please fix.  Add a CI config.  Try AppVeyor or CircleCI.

**Comment by jerriep** [comment]
This repo is deprecated. Please see updated README for more info
