### ISSUE TITLE
GitHub/NuGet Repos need to get cleaned up (Xamarin)

### ISSUE THREAD

**Issue by dagostinelli** [auth0/Xamarin.Auth0Client#31]
I think this needs some cleanup.  

There are two teams in GitHub:
https://github.com/auth0-community
https://github.com/auth0

There are samples spread between them.

My app is Xamarin, so I'll complain specifically about that.

I'm not 100% sure about this, but I think that these are your only Xamarin repos:
https://github.com/auth0-community/auth0-xamarin-oidc-samples
https://github.com/auth0/Xamarin.Auth0Client
https://github.com/auth0/Lock.Xamarin
https://github.com/auth0/Xamarin.Auth

I gathered that https://github.com/auth0-community/auth0-xamarin-oidc-samples is where I should be looking for samples on how to do things.  That is the repo linked-to from the Auth0 web site.  I started there and would have not looked further, but my app is a Xamarin Forms app.  So I went on a hunt for some help with my Xamarin Forms challenges.... (separate issue).  I figured out from all of this that there is no Xamarin Forms support.  You should state that somewhere.

There's the Auth0Client repo. I pull that down and it won't compile.  It has a reference to Xamarin.Auth.Android which isn't in the packages.config file.  The samples don't compile.  It's not clear what we are supposed to do to fix this. (Related: https://github.com/auth0/Xamarin.Auth0Client/issues/29)

What is https://github.com/auth0/Xamarin.Auth for? It's a fork from Xamarin.Auth.  I don't get it.  Moving on...

I gathered from the Auth0 web site that Lock is the latest thing. There's a Lock project for Xamarin (I'm thinking maybe it will have a native feel -- no external web browser) But it's deprecated.  👎 
https://github.com/auth0/Lock.Xamarin

I think this needs some cleanup.

**Comment by jerriep** [comment]
@dagostinelli 

You are right, it is a mess. I am requesting access to all the relevant repositories to add deprecation notices, or remove them where applicable.

The [Xamarin Quickstart](https://auth0.com/docs/quickstart/native/xamarin) is the correct place to start.

There is no Lock for Xamarin. You need to use OpenID Connect. There is also no immediate plans for Xamarin Forms. Will answer on the relevant issue

**Comment by jerriep** [comment]
Cleanup in progress. Most non-used repos marked as deprecated
